// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module scaled_fixed2ieee (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V,
        prescale,
        ap_return
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;
parameter    ap_const_lv32_0 = 32'd0;


input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [28:0] in_V;
input  [8:0] prescale;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] ap_return;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] out_bits_0_V_fu_194_p5;
reg   [31:0] out_bits_0_V_reg_469;
wire   [31:0] p_Result_s_fu_218_p5;
reg   [31:0] p_Result_s_reg_474;
wire   [1:0] i_fu_236_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] c_1_1_fu_280_p3;
wire   [0:0] exitcond_fu_230_p2;
wire   [31:0] c_1_2_fu_288_p3;
wire   [0:0] tmp_24_fu_296_p3;
reg   [0:0] tmp_24_reg_497;
wire    ap_CS_fsm_state3;
wire   [1:0] i_1_fu_304_p2;
reg   [1:0] i_1_reg_501;
wire   [31:0] sh_assign_fu_314_p3;
reg   [31:0] sh_assign_reg_506;
reg   [0:0] isNeg_reg_513;
wire   [31:0] tmp_8_fu_330_p2;
reg   [31:0] tmp_8_reg_519;
wire   [31:0] shift_2_fu_336_p2;
wire    ap_CS_fsm_state4;
wire   [28:0] in_shift_V_fu_370_p3;
wire   [8:0] tmp_3_fu_382_p2;
reg   [8:0] tmp_3_reg_539;
wire   [0:0] tmp_2_fu_377_p2;
wire   [0:0] tmp_6_fu_387_p2;
reg   [0:0] tmp_6_reg_544;
reg   [31:0] c_0_s_reg_88;
reg   [31:0] c_1_s_reg_100;
reg   [1:0] i1_reg_112;
reg   [28:0] in_shift_reg_123;
reg   [31:0] shift_reg_133;
reg   [1:0] i2_reg_145;
reg   [28:0] p_Val2_s_reg_156;
reg   [31:0] shift_1_reg_166;
wire   [15:0] p_Result_1_fu_176_p4;
wire   [16:0] tmp_fu_186_p3;
wire   [12:0] tmp_22_fu_206_p1;
wire   [13:0] tmp_5_fu_210_p3;
wire   [0:0] tmp_23_fu_242_p1;
reg   [31:0] tmp_4_fu_246_p4;
reg   [31:0] tmp_7_fu_255_p4;
wire   [31:0] p_Result_29_fu_264_p3;
reg   [31:0] c_0_fu_272_p3;
wire   [0:0] tmp_25_fu_310_p1;
wire   [31:0] tmp_9_fu_346_p1;
wire   [31:0] sh_assign_1_fu_341_p3;
wire   [31:0] tmp_1_fu_356_p2;
wire   [31:0] tmp_s_fu_350_p2;
wire   [28:0] tmp_27_fu_362_p1;
wire   [28:0] tmp_28_fu_366_p1;
wire    ap_CS_fsm_state5;
wire  signed [31:0] tmp_3_cast_fu_392_p1;
wire   [31:0] newexp_fu_395_p2;
wire   [0:0] tmp_30_fu_401_p3;
wire   [0:0] or_cond_fu_409_p2;
wire   [22:0] phitmp2_fu_418_p4;
wire   [7:0] tmp_31_fu_414_p1;
wire   [7:0] out_exp_V_fu_436_p3;
wire   [22:0] p_Val2_22_fu_428_p3;
wire   [31:0] p_Result_30_fu_444_p4;
wire   [31:0] result_write_assign_fu_454_p1;
reg   [31:0] ap_return_preg;
reg   [4:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_return_preg = 32'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_preg[0] <= 1'b0;
        ap_return_preg[1] <= 1'b0;
        ap_return_preg[2] <= 1'b0;
        ap_return_preg[3] <= 1'b0;
        ap_return_preg[4] <= 1'b0;
        ap_return_preg[5] <= 1'b0;
        ap_return_preg[6] <= 1'b0;
        ap_return_preg[7] <= 1'b0;
        ap_return_preg[8] <= 1'b0;
        ap_return_preg[9] <= 1'b0;
        ap_return_preg[10] <= 1'b0;
        ap_return_preg[11] <= 1'b0;
        ap_return_preg[12] <= 1'b0;
        ap_return_preg[13] <= 1'b0;
        ap_return_preg[14] <= 1'b0;
        ap_return_preg[15] <= 1'b0;
        ap_return_preg[16] <= 1'b0;
        ap_return_preg[17] <= 1'b0;
        ap_return_preg[18] <= 1'b0;
        ap_return_preg[19] <= 1'b0;
        ap_return_preg[20] <= 1'b0;
        ap_return_preg[21] <= 1'b0;
        ap_return_preg[22] <= 1'b0;
        ap_return_preg[23] <= 1'b0;
        ap_return_preg[24] <= 1'b0;
        ap_return_preg[25] <= 1'b0;
        ap_return_preg[26] <= 1'b0;
        ap_return_preg[27] <= 1'b0;
        ap_return_preg[28] <= 1'b0;
        ap_return_preg[29] <= 1'b0;
        ap_return_preg[30] <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
                        ap_return_preg[30 : 0] <= result_write_assign_fu_454_p1[30 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_230_p2 == 1'd0))) begin
        i1_reg_112 <= i_fu_236_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i1_reg_112 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_230_p2 == 1'd1))) begin
        i2_reg_145 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (1'd0 == tmp_24_reg_497) & (1'd1 == tmp_2_fu_377_p2))) begin
        i2_reg_145 <= i_1_reg_501;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_230_p2 == 1'd1))) begin
        in_shift_reg_123 <= in_V;
    end else if (((1'b1 == ap_CS_fsm_state4) & (1'd0 == tmp_24_reg_497) & (1'd1 == tmp_2_fu_377_p2))) begin
        in_shift_reg_123 <= in_shift_V_fu_370_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd0 == tmp_24_reg_497) & (1'd0 == tmp_2_fu_377_p2))) begin
        p_Val2_s_reg_156 <= in_shift_V_fu_370_p3;
    end else if (((1'b1 == ap_CS_fsm_state3) & (tmp_24_fu_296_p3 == 1'd1))) begin
        p_Val2_s_reg_156 <= in_shift_reg_123;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd0 == tmp_24_reg_497) & (1'd0 == tmp_2_fu_377_p2))) begin
        shift_1_reg_166 <= shift_2_fu_336_p2;
    end else if (((1'b1 == ap_CS_fsm_state3) & (tmp_24_fu_296_p3 == 1'd1))) begin
        shift_1_reg_166 <= shift_reg_133;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_230_p2 == 1'd1))) begin
        shift_reg_133 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (1'd0 == tmp_24_reg_497) & (1'd1 == tmp_2_fu_377_p2))) begin
        shift_reg_133 <= shift_2_fu_336_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_230_p2 == 1'd0))) begin
        c_0_s_reg_88 <= c_1_1_fu_280_p3;
        c_1_s_reg_100 <= c_1_2_fu_288_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_1_reg_501 <= i_1_fu_304_p2;
        tmp_24_reg_497 <= i2_reg_145[32'd1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (1'd0 == tmp_24_fu_296_p3))) begin
        isNeg_reg_513 <= sh_assign_fu_314_p3[32'd31];
        sh_assign_reg_506 <= sh_assign_fu_314_p3;
        tmp_8_reg_519 <= tmp_8_fu_330_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        out_bits_0_V_reg_469 <= out_bits_0_V_fu_194_p5;
        p_Result_s_reg_474 <= p_Result_s_fu_218_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & ((tmp_24_reg_497 == 1'd1) | (1'd0 == tmp_2_fu_377_p2)))) begin
        tmp_3_reg_539 <= tmp_3_fu_382_p2;
        tmp_6_reg_544 <= tmp_6_fu_387_p2;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1)) | (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_return = result_write_assign_fu_454_p1;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_230_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & ((tmp_24_reg_497 == 1'd1) | (1'd0 == tmp_2_fu_377_p2)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];


always @ (p_Result_29_fu_264_p3) begin
    if (p_Result_29_fu_264_p3[0] == 1'b1) begin
        c_0_fu_272_p3 = 32'd0;
    end else if (p_Result_29_fu_264_p3[1] == 1'b1) begin
        c_0_fu_272_p3 = 32'd1;
    end else if (p_Result_29_fu_264_p3[2] == 1'b1) begin
        c_0_fu_272_p3 = 32'd2;
    end else if (p_Result_29_fu_264_p3[3] == 1'b1) begin
        c_0_fu_272_p3 = 32'd3;
    end else if (p_Result_29_fu_264_p3[4] == 1'b1) begin
        c_0_fu_272_p3 = 32'd4;
    end else if (p_Result_29_fu_264_p3[5] == 1'b1) begin
        c_0_fu_272_p3 = 32'd5;
    end else if (p_Result_29_fu_264_p3[6] == 1'b1) begin
        c_0_fu_272_p3 = 32'd6;
    end else if (p_Result_29_fu_264_p3[7] == 1'b1) begin
        c_0_fu_272_p3 = 32'd7;
    end else if (p_Result_29_fu_264_p3[8] == 1'b1) begin
        c_0_fu_272_p3 = 32'd8;
    end else if (p_Result_29_fu_264_p3[9] == 1'b1) begin
        c_0_fu_272_p3 = 32'd9;
    end else if (p_Result_29_fu_264_p3[10] == 1'b1) begin
        c_0_fu_272_p3 = 32'd10;
    end else if (p_Result_29_fu_264_p3[11] == 1'b1) begin
        c_0_fu_272_p3 = 32'd11;
    end else if (p_Result_29_fu_264_p3[12] == 1'b1) begin
        c_0_fu_272_p3 = 32'd12;
    end else if (p_Result_29_fu_264_p3[13] == 1'b1) begin
        c_0_fu_272_p3 = 32'd13;
    end else if (p_Result_29_fu_264_p3[14] == 1'b1) begin
        c_0_fu_272_p3 = 32'd14;
    end else if (p_Result_29_fu_264_p3[15] == 1'b1) begin
        c_0_fu_272_p3 = 32'd15;
    end else if (p_Result_29_fu_264_p3[16] == 1'b1) begin
        c_0_fu_272_p3 = 32'd16;
    end else if (p_Result_29_fu_264_p3[17] == 1'b1) begin
        c_0_fu_272_p3 = 32'd17;
    end else if (p_Result_29_fu_264_p3[18] == 1'b1) begin
        c_0_fu_272_p3 = 32'd18;
    end else if (p_Result_29_fu_264_p3[19] == 1'b1) begin
        c_0_fu_272_p3 = 32'd19;
    end else if (p_Result_29_fu_264_p3[20] == 1'b1) begin
        c_0_fu_272_p3 = 32'd20;
    end else if (p_Result_29_fu_264_p3[21] == 1'b1) begin
        c_0_fu_272_p3 = 32'd21;
    end else if (p_Result_29_fu_264_p3[22] == 1'b1) begin
        c_0_fu_272_p3 = 32'd22;
    end else if (p_Result_29_fu_264_p3[23] == 1'b1) begin
        c_0_fu_272_p3 = 32'd23;
    end else if (p_Result_29_fu_264_p3[24] == 1'b1) begin
        c_0_fu_272_p3 = 32'd24;
    end else if (p_Result_29_fu_264_p3[25] == 1'b1) begin
        c_0_fu_272_p3 = 32'd25;
    end else if (p_Result_29_fu_264_p3[26] == 1'b1) begin
        c_0_fu_272_p3 = 32'd26;
    end else if (p_Result_29_fu_264_p3[27] == 1'b1) begin
        c_0_fu_272_p3 = 32'd27;
    end else if (p_Result_29_fu_264_p3[28] == 1'b1) begin
        c_0_fu_272_p3 = 32'd28;
    end else if (p_Result_29_fu_264_p3[29] == 1'b1) begin
        c_0_fu_272_p3 = 32'd29;
    end else if (p_Result_29_fu_264_p3[30] == 1'b1) begin
        c_0_fu_272_p3 = 32'd30;
    end else if (p_Result_29_fu_264_p3[31] == 1'b1) begin
        c_0_fu_272_p3 = 32'd31;
    end else begin
        c_0_fu_272_p3 = 32'd32;
    end
end

assign c_1_1_fu_280_p3 = ((tmp_23_fu_242_p1[0:0] === 1'b1) ? c_0_s_reg_88 : c_0_fu_272_p3);

assign c_1_2_fu_288_p3 = ((tmp_23_fu_242_p1[0:0] === 1'b1) ? c_0_fu_272_p3 : c_1_s_reg_100);

assign exitcond_fu_230_p2 = ((i1_reg_112 == 2'd2) ? 1'b1 : 1'b0);

assign i_1_fu_304_p2 = (i2_reg_145 + 2'd1);

assign i_fu_236_p2 = (i1_reg_112 + 2'd1);

assign in_shift_V_fu_370_p3 = ((isNeg_reg_513[0:0] === 1'b1) ? tmp_27_fu_362_p1 : tmp_28_fu_366_p1);

assign newexp_fu_395_p2 = ($signed(tmp_3_cast_fu_392_p1) - $signed(shift_1_reg_166));

assign or_cond_fu_409_p2 = (tmp_30_fu_401_p3 | tmp_6_reg_544);

assign out_bits_0_V_fu_194_p5 = {{tmp_fu_186_p3}, {ap_const_lv32_0[14:0]}};

assign out_exp_V_fu_436_p3 = ((or_cond_fu_409_p2[0:0] === 1'b1) ? 8'd0 : tmp_31_fu_414_p1);

assign p_Result_1_fu_176_p4 = {{in_V[28:13]}};

assign p_Result_29_fu_264_p3 = ((tmp_23_fu_242_p1[0:0] === 1'b1) ? tmp_4_fu_246_p4 : tmp_7_fu_255_p4);

assign p_Result_30_fu_444_p4 = {{{{1'd0}, {out_exp_V_fu_436_p3}}}, {p_Val2_22_fu_428_p3}};

assign p_Result_s_fu_218_p5 = {{tmp_5_fu_210_p3}, {ap_const_lv32_0[17:0]}};

assign p_Val2_22_fu_428_p3 = ((or_cond_fu_409_p2[0:0] === 1'b1) ? 23'd0 : phitmp2_fu_418_p4);

assign phitmp2_fu_418_p4 = {{p_Val2_s_reg_156[27:5]}};

assign result_write_assign_fu_454_p1 = p_Result_30_fu_444_p4;

assign sh_assign_1_fu_341_p3 = ((isNeg_reg_513[0:0] === 1'b1) ? tmp_8_reg_519 : sh_assign_reg_506);

assign sh_assign_fu_314_p3 = ((tmp_25_fu_310_p1[0:0] === 1'b1) ? c_1_s_reg_100 : c_0_s_reg_88);

assign shift_2_fu_336_p2 = (shift_reg_133 + sh_assign_reg_506);

assign tmp_1_fu_356_p2 = tmp_9_fu_346_p1 >> sh_assign_1_fu_341_p3;

assign tmp_22_fu_206_p1 = in_V[12:0];

assign tmp_23_fu_242_p1 = i1_reg_112[0:0];

assign tmp_24_fu_296_p3 = i2_reg_145[32'd1];

assign tmp_25_fu_310_p1 = i2_reg_145[0:0];

assign tmp_27_fu_362_p1 = tmp_1_fu_356_p2[28:0];

assign tmp_28_fu_366_p1 = tmp_s_fu_350_p2[28:0];

assign tmp_2_fu_377_p2 = ((sh_assign_reg_506 == 32'd16) ? 1'b1 : 1'b0);

assign tmp_30_fu_401_p3 = newexp_fu_395_p2[32'd31];

assign tmp_31_fu_414_p1 = newexp_fu_395_p2[7:0];

assign tmp_3_cast_fu_392_p1 = $signed(tmp_3_reg_539);

assign tmp_3_fu_382_p2 = (9'd127 - prescale);

integer ap_tvar_int_0;

always @ (p_Result_s_reg_474) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            tmp_4_fu_246_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_4_fu_246_p4[ap_tvar_int_0] = p_Result_s_reg_474[31 - ap_tvar_int_0];
        end
    end
end

assign tmp_5_fu_210_p3 = {{tmp_22_fu_206_p1}, {1'd1}};

assign tmp_6_fu_387_p2 = ((in_V == 29'd0) ? 1'b1 : 1'b0);

integer ap_tvar_int_1;

always @ (out_bits_0_V_reg_469) begin
    for (ap_tvar_int_1 = 32 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 31 - 0) begin
            tmp_7_fu_255_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_7_fu_255_p4[ap_tvar_int_1] = out_bits_0_V_reg_469[31 - ap_tvar_int_1];
        end
    end
end

assign tmp_8_fu_330_p2 = (32'd0 - sh_assign_fu_314_p3);

assign tmp_9_fu_346_p1 = in_shift_reg_123;

assign tmp_fu_186_p3 = {{p_Result_1_fu_176_p4}, {1'd1}};

assign tmp_s_fu_350_p2 = tmp_9_fu_346_p1 << sh_assign_1_fu_341_p3;

always @ (posedge ap_clk) begin
    ap_return_preg[31] <= 1'b0;
end

endmodule //scaled_fixed2ieee
