// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="xillybus_wrapper,hls_ip_2017_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.532000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=24,HLS_SYN_FF=4861,HLS_SYN_LUT=3381}" *)

module xillybus_wrapper (
        ap_clk,
        ap_rst,
        in_r_dout,
        in_r_empty_n,
        in_r_read,
        out_r_din,
        out_r_full_n,
        out_r_write,
        debug_ready,
        debug_out,
        debug_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 29'd1;
parameter    ap_ST_fsm_state2 = 29'd2;
parameter    ap_ST_fsm_state3 = 29'd4;
parameter    ap_ST_fsm_state4 = 29'd8;
parameter    ap_ST_fsm_state5 = 29'd16;
parameter    ap_ST_fsm_state6 = 29'd32;
parameter    ap_ST_fsm_state7 = 29'd64;
parameter    ap_ST_fsm_state8 = 29'd128;
parameter    ap_ST_fsm_state9 = 29'd256;
parameter    ap_ST_fsm_state10 = 29'd512;
parameter    ap_ST_fsm_state11 = 29'd1024;
parameter    ap_ST_fsm_state12 = 29'd2048;
parameter    ap_ST_fsm_state13 = 29'd4096;
parameter    ap_ST_fsm_state14 = 29'd8192;
parameter    ap_ST_fsm_state15 = 29'd16384;
parameter    ap_ST_fsm_state16 = 29'd32768;
parameter    ap_ST_fsm_state17 = 29'd65536;
parameter    ap_ST_fsm_state18 = 29'd131072;
parameter    ap_ST_fsm_state19 = 29'd262144;
parameter    ap_ST_fsm_state20 = 29'd524288;
parameter    ap_ST_fsm_state21 = 29'd1048576;
parameter    ap_ST_fsm_state22 = 29'd2097152;
parameter    ap_ST_fsm_state23 = 29'd4194304;
parameter    ap_ST_fsm_state24 = 29'd8388608;
parameter    ap_ST_fsm_state25 = 29'd16777216;
parameter    ap_ST_fsm_state26 = 29'd33554432;
parameter    ap_ST_fsm_state27 = 29'd67108864;
parameter    ap_ST_fsm_state28 = 29'd134217728;
parameter    ap_ST_fsm_state29 = 29'd268435456;

input   ap_clk;
input   ap_rst;
input  [31:0] in_r_dout;
input   in_r_empty_n;
output   in_r_read;
output  [31:0] out_r_din;
input   out_r_full_n;
output   out_r_write;
input  [7:0] debug_ready;
output  [7:0] debug_out;
output   debug_out_ap_vld;

reg in_r_read;
reg[31:0] out_r_din;
reg out_r_write;
reg[7:0] debug_out;
reg debug_out_ap_vld;

wire   [3:0] p_str3_address0;
reg    p_str3_ce0;
wire   [6:0] p_str3_q0;
wire   [1:0] p_str4_address0;
reg    p_str4_ce0;
wire   [6:0] p_str4_q0;
wire   [0:0] p_str5_address0;
reg    p_str5_ce0;
wire   [3:0] p_str5_q0;
wire   [3:0] hls_ref_4oPi_table_s_address0;
reg    hls_ref_4oPi_table_s_ce0;
wire   [99:0] hls_ref_4oPi_table_s_q0;
wire   [7:0] hls_hotbm_second_o_2_address0;
reg    hls_hotbm_second_o_2_ce0;
wire   [29:0] hls_hotbm_second_o_2_q0;
wire   [7:0] hls_hotbm_second_o_3_address0;
reg    hls_hotbm_second_o_3_ce0;
wire   [22:0] hls_hotbm_second_o_3_q0;
wire   [7:0] hls_hotbm_second_o_address0;
reg    hls_hotbm_second_o_ce0;
wire   [14:0] hls_hotbm_second_o_q0;
reg    in_r_blk_n;
(* fsm_encoding = "none" *) reg   [28:0] ap_CS_fsm;
wire    ap_CS_fsm_state3;
reg   [0:0] tmp_i_reg_1141;
wire    ap_CS_fsm_state5;
reg    out_r_blk_n;
wire    ap_CS_fsm_state11;
reg   [0:0] p_0_rec_i9_reg_314;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_i_fu_354_p2;
wire   [3:0] p_rec_i_fu_360_p2;
reg   [3:0] p_rec_i_reg_1145;
wire   [7:0] p_str3_load_cast_fu_366_p1;
reg   [7:0] p_str3_load_cast_reg_1150;
reg    ap_block_state3;
reg   [31:0] x1_reg_1155;
reg   [31:0] tmp_18_reg_1164;
wire    ap_CS_fsm_state6;
wire   [0:0] tmp_i3_fu_384_p2;
reg   [0:0] tmp_i3_reg_1176;
wire   [1:0] p_rec_i8_fu_390_p2;
reg   [1:0] p_rec_i8_reg_1180;
wire   [7:0] p_str4_load_cast_fu_396_p1;
reg   [7:0] p_str4_load_cast_reg_1185;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state10;
wire   [7:0] p_str5_load_cast_fu_414_p1;
reg   [7:0] p_str5_load_cast_reg_1198;
reg    ap_block_state11;
reg   [0:0] results_sign_V_1_reg_1203;
wire   [7:0] loc_V_fu_425_p4;
reg   [7:0] loc_V_reg_1209;
wire   [22:0] loc_V_1_fu_434_p1;
reg   [22:0] loc_V_1_reg_1216;
wire   [0:0] closepath_fu_437_p2;
reg   [0:0] closepath_reg_1222;
wire   [3:0] tmp_9_fu_472_p1;
reg   [3:0] tmp_9_reg_1233;
reg   [79:0] Med_V_reg_1241;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire   [0:0] tmp_10_i_fu_530_p2;
reg   [0:0] tmp_10_i_reg_1256;
reg   [57:0] p_Val2_5_reg_1262;
wire    ap_CS_fsm_state18;
reg   [2:0] tmp_13_i_i_reg_1268;
wire   [2:0] p_Val2_s_fu_555_p3;
reg   [2:0] p_Val2_s_reg_1273;
wire    ap_CS_fsm_state19;
wire   [57:0] p_Val2_7_fu_570_p3;
reg   [57:0] p_Val2_7_reg_1279;
reg   [28:0] p_Result_i2_i_i_reg_1284;
reg   [28:0] Mx_V_reg_1289;
wire    ap_CS_fsm_state20;
wire   [7:0] Ex_V_fu_659_p2;
reg   [7:0] Ex_V_reg_1296;
reg   [0:0] isNeg_reg_1302;
wire   [0:0] tmp_9_i_fu_673_p2;
reg   [0:0] tmp_9_i_reg_1308;
wire   [0:0] tmp_11_i_fu_678_p2;
reg   [0:0] tmp_11_i_reg_1314;
wire   [8:0] sh_assign_fu_692_p3;
reg   [8:0] sh_assign_reg_1320;
wire    ap_CS_fsm_state21;
wire   [0:0] cos_basis_fu_730_p10;
reg   [0:0] cos_basis_reg_1326;
wire    ap_CS_fsm_state22;
wire   [21:0] p_Val2_12_fu_761_p1;
reg   [21:0] p_Val2_12_reg_1333;
reg   [14:0] tmp_i1_i_reg_1338;
reg   [14:0] tmp_24_i_i_reg_1358;
wire    ap_CS_fsm_state23;
reg   [28:0] p_Val2_15_reg_1363;
reg   [22:0] hls_hotbm_second_o_5_reg_1368;
reg  signed [14:0] hls_hotbm_second_o_7_reg_1373;
reg   [21:0] tmp_29_i_i_reg_1378;
wire    ap_CS_fsm_state24;
reg   [13:0] tmp_31_i_i_reg_1383;
wire   [28:0] Mx_V_read_assign_fu_855_p3;
reg   [28:0] Mx_V_read_assign_reg_1388;
wire    ap_CS_fsm_state25;
wire   [29:0] r_V_fu_876_p2;
reg  signed [29:0] r_V_reg_1393;
wire    ap_CS_fsm_state26;
reg   [28:0] result_V_reg_1408;
wire    ap_CS_fsm_state27;
wire   [8:0] r_V_1_fu_915_p2;
reg   [8:0] r_V_1_reg_1413;
wire   [31:0] grp_scaled_fixed2ieee_fu_328_ap_return;
reg   [31:0] resultf_reg_1418;
wire    ap_CS_fsm_state28;
wire    grp_scaled_fixed2ieee_fu_328_ap_done;
wire    grp_scaled_fixed2ieee_fu_328_ap_start;
wire    grp_scaled_fixed2ieee_fu_328_ap_idle;
wire    grp_scaled_fixed2ieee_fu_328_ap_ready;
wire    grp_xilly_decprint_fu_334_ap_start;
wire    grp_xilly_decprint_fu_334_ap_done;
wire    grp_xilly_decprint_fu_334_ap_idle;
wire    grp_xilly_decprint_fu_334_ap_ready;
wire   [7:0] grp_xilly_decprint_fu_334_debug_out;
wire    grp_xilly_decprint_fu_334_debug_out_ap_vld;
reg   [3:0] p_0_rec_i_reg_292;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state4;
wire   [0:0] tmp_5_fu_370_p1;
reg   [1:0] p_0_rec_i2_reg_303;
wire    ap_CS_fsm_state8;
wire   [0:0] tmp_6_fu_400_p1;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state12;
wire   [0:0] tmp_17_fu_482_p1;
reg    ap_reg_grp_scaled_fixed2ieee_fu_328_ap_start;
reg    ap_reg_grp_xilly_decprint_fu_334_ap_start;
wire   [31:0] p_0_rec_i_cast_fu_349_p1;
wire   [31:0] p_0_rec_i2_cast_fu_379_p1;
wire   [31:0] p_0_rec_i9_cast_fu_409_p1;
wire   [31:0] tmp_3_i_i_i_fu_467_p1;
wire   [31:0] tmp_27_i_i_fu_789_p1;
wire   [31:0] y1_fu_476_p2;
wire   [31:0] p_Result_28_fu_1111_p4;
wire   [7:0] expv_op_i_fu_443_p2;
wire   [7:0] addr_V_fu_449_p3;
wire   [3:0] tmp_4_fu_457_p4;
wire   [99:0] tmp_5_i_i_i_fu_491_p1;
wire   [99:0] r_V_4_fu_494_p2;
wire   [23:0] p_Result_21_fu_510_p3;
wire   [79:0] grp_fu_524_p0;
wire   [23:0] grp_fu_524_p1;
wire   [103:0] grp_fu_524_p2;
wire   [0:0] tmp_10_fu_561_p1;
wire   [57:0] p_Val2_i_i_fu_565_p2;
wire   [7:0] p_i_i_fu_587_p2;
wire   [29:0] p_Result_22_fu_599_p3;
reg   [29:0] p_Result_23_fu_606_p4;
wire   [31:0] p_Result_24_fu_616_p3;
reg   [31:0] val_assign_fu_624_p3;
wire   [4:0] Mx_zeros_V_fu_632_p1;
wire   [57:0] tmp_14_i_i_fu_636_p1;
wire   [57:0] p_Val2_9_fu_640_p2;
wire   [7:0] storemerge_i_i_fu_592_p3;
wire   [7:0] tmp_17_i_i_fu_655_p1;
wire  signed [8:0] sh_i_cast_fu_683_p1;
wire   [8:0] tmp_19_i_i_fu_686_p2;
wire  signed [28:0] sh_assign_2_i_cast_fu_702_p1;
wire   [28:0] tmp_21_i_i_fu_708_p2;
wire   [31:0] tmp_20_i_i_fu_705_p1;
wire  signed [31:0] sh_assign_2_i_cast1_fu_699_p1;
wire   [31:0] tmp_21_i_i_cast_fu_713_p1;
wire   [31:0] tmp_22_i_i_fu_717_p2;
wire   [31:0] ssdm_int_V_write_ass_fu_723_p3;
wire   [0:0] sin_basis_fu_775_p2;
wire   [6:0] p_Result_i_i_fu_751_p4;
wire   [7:0] p_Result_25_fu_781_p3;
wire   [29:0] p_Val2_13_fu_1122_p2;
wire  signed [22:0] p_Val2_1_fu_824_p0;
wire   [21:0] p_Val2_1_fu_824_p1;
wire   [44:0] p_Val2_1_fu_824_p2;
wire  signed [29:0] p_Val2_6_fu_1129_p2;
wire  signed [29:0] tmp_32_i_i_fu_861_p1;
wire  signed [29:0] tmp_33_i_i_fu_864_p1;
wire   [29:0] p_Val2_16_fu_867_p2;
wire  signed [29:0] tmp_35_i_i_cast_fu_873_p1;
wire   [28:0] grp_fu_888_p1;
wire   [57:0] grp_fu_888_p2;
wire   [7:0] p_Ex_V_ret_i_fu_894_p3;
wire  signed [8:0] rhs_V_1_fu_911_p1;
wire   [31:0] p_Val2_18_fu_922_p1;
wire   [3:0] p_Result_27_fu_947_p3;
wire   [0:0] tmp_fu_953_p18;
wire   [0:0] tmp_1_fu_991_p18;
wire   [0:0] tmp_8_i_fu_1029_p3;
wire   [0:0] p_Result_26_fu_925_p3;
wire   [0:0] p_Result_i_fu_1036_p2;
wire   [0:0] not_tmp_i_fu_1046_p2;
wire   [0:0] or_cond_i_fu_1042_p2;
wire   [0:0] p_Result_i_29_fu_1051_p2;
wire   [0:0] not_or_cond_i_demorg_fu_1064_p2;
wire   [0:0] not_or_cond_i_fu_1068_p2;
wire   [0:0] tmp_2_fu_1082_p2;
wire   [7:0] p_Result_1_i_cast_fu_1074_p3;
wire   [7:0] loc_V_2_fu_933_p4;
wire   [22:0] p_Result_2_i_cast_fu_1095_p3;
wire   [22:0] loc_V_3_fu_943_p1;
wire   [0:0] p_Result_s_fu_1057_p3;
wire   [7:0] ret_V_3_fu_1087_p3;
wire   [22:0] ret_V_4_fu_1103_p3;
wire   [14:0] p_Val2_13_fu_1122_p0;
wire   [29:0] OP1_V_3_fu_796_p1;
wire   [14:0] p_Val2_13_fu_1122_p1;
wire   [14:0] p_Val2_6_fu_1129_p0;
reg   [28:0] ap_NS_fsm;
wire   [103:0] grp_fu_524_p00;
wire   [103:0] grp_fu_524_p10;
wire   [57:0] grp_fu_888_p10;
wire   [44:0] p_Val2_1_fu_824_p10;
wire   [29:0] p_Val2_6_fu_1129_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 29'd1;
#0 ap_reg_grp_scaled_fixed2ieee_fu_328_ap_start = 1'b0;
#0 ap_reg_grp_xilly_decprint_fu_334_ap_start = 1'b0;
end

xillybus_wrapper_cud #(
    .DataWidth( 7 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
p_str3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_str3_address0),
    .ce0(p_str3_ce0),
    .q0(p_str3_q0)
);

xillybus_wrapper_dEe #(
    .DataWidth( 7 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_str4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_str4_address0),
    .ce0(p_str4_ce0),
    .q0(p_str4_q0)
);

xillybus_wrapper_eOg #(
    .DataWidth( 4 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
p_str5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_str5_address0),
    .ce0(p_str5_ce0),
    .q0(p_str5_q0)
);

xillybus_wrapper_fYi #(
    .DataWidth( 100 ),
    .AddressRange( 13 ),
    .AddressWidth( 4 ))
hls_ref_4oPi_table_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_ref_4oPi_table_s_address0),
    .ce0(hls_ref_4oPi_table_s_ce0),
    .q0(hls_ref_4oPi_table_s_q0)
);

xillybus_wrapper_g8j #(
    .DataWidth( 30 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
hls_hotbm_second_o_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_hotbm_second_o_2_address0),
    .ce0(hls_hotbm_second_o_2_ce0),
    .q0(hls_hotbm_second_o_2_q0)
);

xillybus_wrapper_hbi #(
    .DataWidth( 23 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
hls_hotbm_second_o_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_hotbm_second_o_3_address0),
    .ce0(hls_hotbm_second_o_3_ce0),
    .q0(hls_hotbm_second_o_3_q0)
);

xillybus_wrapper_ibs #(
    .DataWidth( 15 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
hls_hotbm_second_o_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_hotbm_second_o_address0),
    .ce0(hls_hotbm_second_o_ce0),
    .q0(hls_hotbm_second_o_q0)
);

scaled_fixed2ieee grp_scaled_fixed2ieee_fu_328(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_scaled_fixed2ieee_fu_328_ap_start),
    .ap_done(grp_scaled_fixed2ieee_fu_328_ap_done),
    .ap_idle(grp_scaled_fixed2ieee_fu_328_ap_idle),
    .ap_ready(grp_scaled_fixed2ieee_fu_328_ap_ready),
    .in_V(result_V_reg_1408),
    .prescale(r_V_1_reg_1413),
    .ap_return(grp_scaled_fixed2ieee_fu_328_ap_return)
);

xilly_decprint grp_xilly_decprint_fu_334(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xilly_decprint_fu_334_ap_start),
    .ap_done(grp_xilly_decprint_fu_334_ap_done),
    .ap_idle(grp_xilly_decprint_fu_334_ap_idle),
    .ap_ready(grp_xilly_decprint_fu_334_ap_ready),
    .val_r(x1_reg_1155),
    .debug_ready(debug_ready),
    .debug_out(grp_xilly_decprint_fu_334_debug_out),
    .debug_out_ap_vld(grp_xilly_decprint_fu_334_debug_out_ap_vld)
);

xillybus_wrapper_jbC #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 80 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 104 ))
xillybus_wrapper_jbC_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_524_p0),
    .din1(grp_fu_524_p1),
    .ce(1'b1),
    .dout(grp_fu_524_p2)
);

xillybus_wrapper_kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
xillybus_wrapper_kbM_U8(
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd1),
    .din4(1'd0),
    .din5(1'd0),
    .din6(1'd1),
    .din7(1'd1),
    .din8(1'd0),
    .din9(p_Val2_s_reg_1273),
    .dout(cos_basis_fu_730_p10)
);

xillybus_wrapper_lbW #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 29 ),
    .dout_WIDTH( 58 ))
xillybus_wrapper_lbW_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_V_reg_1393),
    .din1(grp_fu_888_p1),
    .ce(1'b1),
    .dout(grp_fu_888_p2)
);

xillybus_wrapper_mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
xillybus_wrapper_mb6_U10(
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd1),
    .din8(1'd0),
    .din9(1'd0),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd1),
    .din14(1'd0),
    .din15(1'd0),
    .din16(1'd0),
    .din17(p_Result_27_fu_947_p3),
    .dout(tmp_fu_953_p18)
);

xillybus_wrapper_mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
xillybus_wrapper_mb6_U11(
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(1'd1),
    .din9(1'd1),
    .din10(1'd0),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd0),
    .din14(1'd1),
    .din15(1'd0),
    .din16(1'd0),
    .din17(p_Result_27_fu_947_p3),
    .dout(tmp_1_fu_991_p18)
);

xillybus_wrapper_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
xillybus_wrapper_ncg_U12(
    .din0(p_Val2_13_fu_1122_p0),
    .din1(p_Val2_13_fu_1122_p1),
    .dout(p_Val2_13_fu_1122_p2)
);

xillybus_wrapper_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
xillybus_wrapper_ocq_U13(
    .din0(p_Val2_6_fu_1129_p0),
    .din1(hls_hotbm_second_o_7_reg_1373),
    .dout(p_Val2_6_fu_1129_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_scaled_fixed2ieee_fu_328_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state27)) begin
            ap_reg_grp_scaled_fixed2ieee_fu_328_ap_start <= 1'b1;
        end else if ((1'b1 == grp_scaled_fixed2ieee_fu_328_ap_ready)) begin
            ap_reg_grp_scaled_fixed2ieee_fu_328_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_xilly_decprint_fu_334_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == tmp_i3_reg_1176))) begin
            ap_reg_grp_xilly_decprint_fu_334_ap_start <= 1'b1;
        end else if ((1'b1 == grp_xilly_decprint_fu_334_ap_ready)) begin
            ap_reg_grp_xilly_decprint_fu_334_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (1'd1 == tmp_6_fu_400_p1))) begin
        p_0_rec_i2_reg_303 <= p_rec_i8_reg_1180;
    end else if (((1'b1 == ap_CS_fsm_state5) & (in_r_empty_n == 1'b1))) begin
        p_0_rec_i2_reg_303 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (1'd1 == tmp_17_fu_482_p1))) begin
        p_0_rec_i9_reg_314 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state9) & (grp_xilly_decprint_fu_334_ap_done == 1'b1))) begin
        p_0_rec_i9_reg_314 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd1 == tmp_5_fu_370_p1))) begin
        p_0_rec_i_reg_292 <= p_rec_i_reg_1145;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        p_0_rec_i_reg_292 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        Ex_V_reg_1296 <= Ex_V_fu_659_p2;
        Mx_V_reg_1289 <= {{p_Val2_9_fu_640_p2[57:29]}};
        isNeg_reg_1302 <= Ex_V_fu_659_p2[32'd7];
        tmp_11_i_reg_1314 <= tmp_11_i_fu_678_p2;
        tmp_9_i_reg_1308 <= tmp_9_i_fu_673_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        Med_V_reg_1241 <= {{r_V_4_fu_494_p2[99:20]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        Mx_V_read_assign_reg_1388 <= Mx_V_read_assign_fu_855_p3;
        r_V_reg_1393 <= r_V_fu_876_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (1'd1 == p_0_rec_i9_reg_314) & ~((1'd1 == p_0_rec_i9_reg_314) & (1'b0 == out_r_full_n)))) begin
        closepath_reg_1222 <= closepath_fu_437_p2;
        loc_V_1_reg_1216 <= loc_V_1_fu_434_p1;
        loc_V_reg_1209 <= {{tmp_18_reg_1164[30:23]}};
        results_sign_V_1_reg_1203 <= tmp_18_reg_1164[32'd31];
        tmp_9_reg_1233 <= tmp_9_fu_472_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        cos_basis_reg_1326 <= cos_basis_fu_730_p10;
        p_Val2_12_reg_1333 <= p_Val2_12_fu_761_p1;
        tmp_i1_i_reg_1338 <= {{ssdm_int_V_write_ass_fu_723_p3[21:7]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        hls_hotbm_second_o_5_reg_1368 <= hls_hotbm_second_o_3_q0;
        hls_hotbm_second_o_7_reg_1373 <= hls_hotbm_second_o_q0;
        p_Val2_15_reg_1363 <= {{hls_hotbm_second_o_2_q0[29:1]}};
        tmp_24_i_i_reg_1358 <= {{p_Val2_13_fu_1122_p2[29:15]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        p_Result_i2_i_i_reg_1284 <= {{p_Val2_7_fu_570_p3[57:29]}};
        p_Val2_7_reg_1279 <= p_Val2_7_fu_570_p3;
        p_Val2_s_reg_1273 <= p_Val2_s_fu_555_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        p_Val2_5_reg_1262 <= {{grp_fu_524_p2[76:19]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_rec_i8_reg_1180 <= p_rec_i8_fu_390_p2;
        tmp_i3_reg_1176 <= tmp_i3_fu_384_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_rec_i_reg_1145 <= p_rec_i_fu_360_p2;
        tmp_i_reg_1141 <= tmp_i_fu_354_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & ~((tmp_i_reg_1141 == 1'd1) & (1'b0 == in_r_empty_n)))) begin
        p_str3_load_cast_reg_1150[6 : 0] <= p_str3_load_cast_fu_366_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        p_str4_load_cast_reg_1185[6 : 0] <= p_str4_load_cast_fu_396_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & ~((1'd1 == p_0_rec_i9_reg_314) & (1'b0 == out_r_full_n)))) begin
        p_str5_load_cast_reg_1198[3 : 0] <= p_str5_load_cast_fu_414_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        r_V_1_reg_1413 <= r_V_1_fu_915_p2;
        result_V_reg_1408 <= {{grp_fu_888_p2[57:29]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state28) & (grp_scaled_fixed2ieee_fu_328_ap_done == 1'b1))) begin
        resultf_reg_1418 <= grp_scaled_fixed2ieee_fu_328_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        sh_assign_reg_1320 <= sh_assign_fu_692_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        tmp_10_i_reg_1256 <= tmp_10_i_fu_530_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) & (closepath_reg_1222 == 1'd0))) begin
        tmp_13_i_i_reg_1268 <= {{grp_fu_524_p2[79:77]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (in_r_empty_n == 1'b1))) begin
        tmp_18_reg_1164 <= in_r_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        tmp_29_i_i_reg_1378 <= {{p_Val2_1_fu_824_p2[44:23]}};
        tmp_31_i_i_reg_1383 <= {{p_Val2_6_fu_1129_p2[29:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_i_reg_1141 == 1'd1) & ~((tmp_i_reg_1141 == 1'd1) & (1'b0 == in_r_empty_n)))) begin
        x1_reg_1155 <= in_r_dout;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (1'd1 == tmp_17_fu_482_p1))) begin
        debug_out = p_str5_load_cast_reg_1198;
    end else if (((1'b1 == ap_CS_fsm_state8) & (1'd1 == tmp_6_fu_400_p1))) begin
        debug_out = p_str4_load_cast_reg_1185;
    end else if (((1'b1 == ap_CS_fsm_state4) & (1'd1 == tmp_5_fu_370_p1))) begin
        debug_out = p_str3_load_cast_reg_1150;
    end else if (((1'b1 == ap_CS_fsm_state9) & (1'b1 == grp_xilly_decprint_fu_334_debug_out_ap_vld))) begin
        debug_out = grp_xilly_decprint_fu_334_debug_out;
    end else begin
        debug_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (1'd1 == tmp_5_fu_370_p1)) | ((1'b1 == ap_CS_fsm_state8) & (1'd1 == tmp_6_fu_400_p1)) | ((1'b1 == ap_CS_fsm_state12) & (1'd1 == tmp_17_fu_482_p1)))) begin
        debug_out_ap_vld = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        debug_out_ap_vld = grp_xilly_decprint_fu_334_debug_out_ap_vld;
    end else begin
        debug_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        hls_hotbm_second_o_2_ce0 = 1'b1;
    end else begin
        hls_hotbm_second_o_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        hls_hotbm_second_o_3_ce0 = 1'b1;
    end else begin
        hls_hotbm_second_o_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        hls_hotbm_second_o_ce0 = 1'b1;
    end else begin
        hls_hotbm_second_o_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & ~((1'd1 == p_0_rec_i9_reg_314) & (1'b0 == out_r_full_n)))) begin
        hls_ref_4oPi_table_s_ce0 = 1'b1;
    end else begin
        hls_ref_4oPi_table_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (tmp_i_reg_1141 == 1'd1)) | (1'b1 == ap_CS_fsm_state5))) begin
        in_r_blk_n = in_r_empty_n;
    end else begin
        in_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (tmp_i_reg_1141 == 1'd1) & ~((tmp_i_reg_1141 == 1'd1) & (1'b0 == in_r_empty_n))) | ((1'b1 == ap_CS_fsm_state5) & (in_r_empty_n == 1'b1)))) begin
        in_r_read = 1'b1;
    end else begin
        in_r_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state11) & (1'd1 == p_0_rec_i9_reg_314)) | (1'b1 == ap_CS_fsm_state29))) begin
        out_r_blk_n = out_r_full_n;
    end else begin
        out_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state29) & (out_r_full_n == 1'b1))) begin
        out_r_din = p_Result_28_fu_1111_p4;
    end else if (((1'b1 == ap_CS_fsm_state11) & (1'd1 == p_0_rec_i9_reg_314) & ~((1'd1 == p_0_rec_i9_reg_314) & (1'b0 == out_r_full_n)))) begin
        out_r_din = y1_fu_476_p2;
    end else begin
        out_r_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state11) & (1'd1 == p_0_rec_i9_reg_314) & ~((1'd1 == p_0_rec_i9_reg_314) & (1'b0 == out_r_full_n))) | ((1'b1 == ap_CS_fsm_state29) & (out_r_full_n == 1'b1)))) begin
        out_r_write = 1'b1;
    end else begin
        out_r_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_str3_ce0 = 1'b1;
    end else begin
        p_str3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_str4_ce0 = 1'b1;
    end else begin
        p_str4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        p_str5_ce0 = 1'b1;
    end else begin
        p_str5_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & ~((tmp_i_reg_1141 == 1'd1) & (1'b0 == in_r_empty_n)) & (tmp_i_reg_1141 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((1'b1 == ap_CS_fsm_state3) & (tmp_i_reg_1141 == 1'd1) & ~((tmp_i_reg_1141 == 1'd1) & (1'b0 == in_r_empty_n)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (1'd1 == tmp_5_fu_370_p1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (in_r_empty_n == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (tmp_i3_reg_1176 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (1'd1 == tmp_6_fu_400_p1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_xilly_decprint_fu_334_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & ~((1'd1 == p_0_rec_i9_reg_314) & (1'b0 == out_r_full_n)) & (p_0_rec_i9_reg_314 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((1'b1 == ap_CS_fsm_state11) & (1'd1 == p_0_rec_i9_reg_314) & ~((1'd1 == p_0_rec_i9_reg_314) & (1'b0 == out_r_full_n)))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (1'd1 == tmp_17_fu_482_p1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if (((1'b1 == ap_CS_fsm_state28) & (grp_scaled_fixed2ieee_fu_328_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        ap_ST_fsm_state29 : begin
            if (((1'b1 == ap_CS_fsm_state29) & (out_r_full_n == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Ex_V_fu_659_p2 = (storemerge_i_i_fu_592_p3 - tmp_17_i_i_fu_655_p1);

assign Mx_V_read_assign_fu_855_p3 = ((cos_basis_reg_1326[0:0] === 1'b1) ? 29'd536870911 : Mx_V_reg_1289);

assign Mx_zeros_V_fu_632_p1 = val_assign_fu_624_p3[4:0];

assign OP1_V_3_fu_796_p1 = tmp_i1_i_reg_1338;

assign addr_V_fu_449_p3 = ((closepath_fu_437_p2[0:0] === 1'b1) ? 8'd63 : expv_op_i_fu_443_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state11 = ((1'd1 == p_0_rec_i9_reg_314) & (1'b0 == out_r_full_n));
end

always @ (*) begin
    ap_block_state3 = ((tmp_i_reg_1141 == 1'd1) & (1'b0 == in_r_empty_n));
end

assign closepath_fu_437_p2 = ((loc_V_fu_425_p4 < 8'd126) ? 1'b1 : 1'b0);

assign expv_op_i_fu_443_p2 = ($signed(8'd194) + $signed(loc_V_fu_425_p4));

assign grp_fu_524_p0 = grp_fu_524_p00;

assign grp_fu_524_p00 = Med_V_reg_1241;

assign grp_fu_524_p1 = grp_fu_524_p10;

assign grp_fu_524_p10 = p_Result_21_fu_510_p3;

assign grp_fu_888_p1 = grp_fu_888_p10;

assign grp_fu_888_p10 = Mx_V_read_assign_reg_1388;

assign grp_scaled_fixed2ieee_fu_328_ap_start = ap_reg_grp_scaled_fixed2ieee_fu_328_ap_start;

assign grp_xilly_decprint_fu_334_ap_start = ap_reg_grp_xilly_decprint_fu_334_ap_start;

assign hls_hotbm_second_o_2_address0 = tmp_27_i_i_fu_789_p1;

assign hls_hotbm_second_o_3_address0 = tmp_27_i_i_fu_789_p1;

assign hls_hotbm_second_o_address0 = tmp_27_i_i_fu_789_p1;

assign hls_ref_4oPi_table_s_address0 = tmp_3_i_i_i_fu_467_p1;

assign loc_V_1_fu_434_p1 = tmp_18_reg_1164[22:0];

assign loc_V_2_fu_933_p4 = {{p_Val2_18_fu_922_p1[30:23]}};

assign loc_V_3_fu_943_p1 = p_Val2_18_fu_922_p1[22:0];

assign loc_V_fu_425_p4 = {{tmp_18_reg_1164[30:23]}};

assign not_or_cond_i_demorg_fu_1064_p2 = (tmp_9_i_reg_1308 & tmp_10_i_reg_1256);

assign not_or_cond_i_fu_1068_p2 = (not_or_cond_i_demorg_fu_1064_p2 ^ 1'd1);

assign not_tmp_i_fu_1046_p2 = (tmp_11_i_reg_1314 ^ 1'd1);

assign or_cond_i_fu_1042_p2 = (tmp_9_i_reg_1308 & tmp_10_i_reg_1256);

assign p_0_rec_i2_cast_fu_379_p1 = p_0_rec_i2_reg_303;

assign p_0_rec_i9_cast_fu_409_p1 = p_0_rec_i9_reg_314;

assign p_0_rec_i_cast_fu_349_p1 = p_0_rec_i_reg_292;

assign p_Ex_V_ret_i_fu_894_p3 = ((cos_basis_reg_1326[0:0] === 1'b1) ? 8'd0 : Ex_V_reg_1296);

assign p_Result_1_i_cast_fu_1074_p3 = ((not_or_cond_i_fu_1068_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_Result_21_fu_510_p3 = {{1'd1}, {loc_V_1_reg_1216}};

assign p_Result_22_fu_599_p3 = {{p_Result_i2_i_i_reg_1284}, {1'd1}};

integer ap_tvar_int_0;

always @ (p_Result_22_fu_599_p3) begin
    for (ap_tvar_int_0 = 30 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 29 - 0) begin
            p_Result_23_fu_606_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_23_fu_606_p4[ap_tvar_int_0] = p_Result_22_fu_599_p3[29 - ap_tvar_int_0];
        end
    end
end

assign p_Result_24_fu_616_p3 = {{2'd3}, {p_Result_23_fu_606_p4}};

assign p_Result_25_fu_781_p3 = {{sin_basis_fu_775_p2}, {p_Result_i_i_fu_751_p4}};

assign p_Result_26_fu_925_p3 = p_Val2_18_fu_922_p1[32'd31];

assign p_Result_27_fu_947_p3 = {{results_sign_V_1_reg_1203}, {p_Val2_s_reg_1273}};

assign p_Result_28_fu_1111_p4 = {{{p_Result_s_fu_1057_p3}, {ret_V_3_fu_1087_p3}}, {ret_V_4_fu_1103_p3}};

assign p_Result_2_i_cast_fu_1095_p3 = ((not_or_cond_i_fu_1068_p2[0:0] === 1'b1) ? 23'd8388607 : 23'd0);

assign p_Result_i_29_fu_1051_p2 = (p_Result_i_fu_1036_p2 & not_tmp_i_fu_1046_p2);

assign p_Result_i_fu_1036_p2 = (tmp_8_i_fu_1029_p3 | p_Result_26_fu_925_p3);

assign p_Result_i_i_fu_751_p4 = {{ssdm_int_V_write_ass_fu_723_p3[28:22]}};

assign p_Result_s_fu_1057_p3 = ((or_cond_i_fu_1042_p2[0:0] === 1'b1) ? results_sign_V_1_reg_1203 : p_Result_i_29_fu_1051_p2);

assign p_Val2_12_fu_761_p1 = ssdm_int_V_write_ass_fu_723_p3[21:0];

assign p_Val2_13_fu_1122_p0 = OP1_V_3_fu_796_p1;

assign p_Val2_13_fu_1122_p1 = OP1_V_3_fu_796_p1;

assign p_Val2_16_fu_867_p2 = ($signed(tmp_32_i_i_fu_861_p1) + $signed(tmp_33_i_i_fu_864_p1));

assign p_Val2_18_fu_922_p1 = resultf_reg_1418;

assign p_Val2_1_fu_824_p0 = hls_hotbm_second_o_5_reg_1368;

assign p_Val2_1_fu_824_p1 = p_Val2_1_fu_824_p10;

assign p_Val2_1_fu_824_p10 = p_Val2_12_reg_1333;

assign p_Val2_1_fu_824_p2 = ($signed(p_Val2_1_fu_824_p0) * $signed({{1'b0}, {p_Val2_1_fu_824_p1}}));

assign p_Val2_6_fu_1129_p0 = p_Val2_6_fu_1129_p00;

assign p_Val2_6_fu_1129_p00 = tmp_24_i_i_reg_1358;

assign p_Val2_7_fu_570_p3 = ((tmp_10_fu_561_p1[0:0] === 1'b1) ? p_Val2_i_i_fu_565_p2 : p_Val2_5_reg_1262);

assign p_Val2_9_fu_640_p2 = p_Val2_7_reg_1279 << tmp_14_i_i_fu_636_p1;

assign p_Val2_i_i_fu_565_p2 = (58'd0 - p_Val2_5_reg_1262);

assign p_Val2_s_fu_555_p3 = ((closepath_reg_1222[0:0] === 1'b1) ? 3'd0 : tmp_13_i_i_reg_1268);

assign p_i_i_fu_587_p2 = ($signed(8'd131) + $signed(loc_V_reg_1209));

assign p_rec_i8_fu_390_p2 = (p_0_rec_i2_reg_303 + 2'd1);

assign p_rec_i_fu_360_p2 = (p_0_rec_i_reg_292 + 4'd1);

assign p_str3_address0 = p_0_rec_i_cast_fu_349_p1;

assign p_str3_load_cast_fu_366_p1 = p_str3_q0;

assign p_str4_address0 = p_0_rec_i2_cast_fu_379_p1;

assign p_str4_load_cast_fu_396_p1 = p_str4_q0;

assign p_str5_address0 = p_0_rec_i9_cast_fu_409_p1;

assign p_str5_load_cast_fu_414_p1 = p_str5_q0;

assign r_V_1_fu_915_p2 = ($signed(9'd0) - $signed(rhs_V_1_fu_911_p1));

assign r_V_4_fu_494_p2 = hls_ref_4oPi_table_s_q0 << tmp_5_i_i_i_fu_491_p1;

assign r_V_fu_876_p2 = ($signed(p_Val2_16_fu_867_p2) + $signed(tmp_35_i_i_cast_fu_873_p1));

assign ret_V_3_fu_1087_p3 = ((tmp_2_fu_1082_p2[0:0] === 1'b1) ? p_Result_1_i_cast_fu_1074_p3 : loc_V_2_fu_933_p4);

assign ret_V_4_fu_1103_p3 = ((tmp_2_fu_1082_p2[0:0] === 1'b1) ? p_Result_2_i_cast_fu_1095_p3 : loc_V_3_fu_943_p1);

assign rhs_V_1_fu_911_p1 = $signed(p_Ex_V_ret_i_fu_894_p3);

assign sh_assign_2_i_cast1_fu_699_p1 = $signed(sh_assign_reg_1320);

assign sh_assign_2_i_cast_fu_702_p1 = $signed(sh_assign_reg_1320);

assign sh_assign_fu_692_p3 = ((isNeg_reg_1302[0:0] === 1'b1) ? tmp_19_i_i_fu_686_p2 : sh_i_cast_fu_683_p1);

assign sh_i_cast_fu_683_p1 = $signed(Ex_V_reg_1296);

assign sin_basis_fu_775_p2 = (cos_basis_fu_730_p10 ^ 1'd1);

assign ssdm_int_V_write_ass_fu_723_p3 = ((isNeg_reg_1302[0:0] === 1'b1) ? tmp_21_i_i_cast_fu_713_p1 : tmp_22_i_i_fu_717_p2);

assign storemerge_i_i_fu_592_p3 = ((closepath_reg_1222[0:0] === 1'b1) ? p_i_i_fu_587_p2 : 8'd0);

assign tmp_10_fu_561_p1 = p_Val2_s_fu_555_p3[0:0];

assign tmp_10_i_fu_530_p2 = ((loc_V_1_reg_1216 == 23'd0) ? 1'b1 : 1'b0);

assign tmp_11_i_fu_678_p2 = ((loc_V_reg_1209 == 8'd255) ? 1'b1 : 1'b0);

assign tmp_14_i_i_fu_636_p1 = Mx_zeros_V_fu_632_p1;

assign tmp_17_fu_482_p1 = debug_ready[0:0];

assign tmp_17_i_i_fu_655_p1 = Mx_zeros_V_fu_632_p1;

assign tmp_19_i_i_fu_686_p2 = ($signed(9'd0) - $signed(sh_i_cast_fu_683_p1));

assign tmp_20_i_i_fu_705_p1 = Mx_V_reg_1289;

assign tmp_21_i_i_cast_fu_713_p1 = tmp_21_i_i_fu_708_p2;

assign tmp_21_i_i_fu_708_p2 = Mx_V_reg_1289 >> sh_assign_2_i_cast_fu_702_p1;

assign tmp_22_i_i_fu_717_p2 = tmp_20_i_i_fu_705_p1 << sh_assign_2_i_cast1_fu_699_p1;

assign tmp_27_i_i_fu_789_p1 = p_Result_25_fu_781_p3;

assign tmp_2_fu_1082_p2 = (or_cond_i_fu_1042_p2 | tmp_11_i_reg_1314);

assign tmp_32_i_i_fu_861_p1 = $signed(p_Val2_15_reg_1363);

assign tmp_33_i_i_fu_864_p1 = $signed(tmp_29_i_i_reg_1378);

assign tmp_35_i_i_cast_fu_873_p1 = $signed(tmp_31_i_i_reg_1383);

assign tmp_3_i_i_i_fu_467_p1 = tmp_4_fu_457_p4;

assign tmp_4_fu_457_p4 = {{addr_V_fu_449_p3[7:4]}};

assign tmp_5_fu_370_p1 = debug_ready[0:0];

assign tmp_5_i_i_i_fu_491_p1 = tmp_9_reg_1233;

assign tmp_6_fu_400_p1 = debug_ready[0:0];

assign tmp_8_i_fu_1029_p3 = ((cos_basis_reg_1326[0:0] === 1'b1) ? tmp_fu_953_p18 : tmp_1_fu_991_p18);

assign tmp_9_fu_472_p1 = addr_V_fu_449_p3[3:0];

assign tmp_9_i_fu_673_p2 = ((loc_V_reg_1209 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_i3_fu_384_p2 = ((p_0_rec_i2_reg_303 == 2'd3) ? 1'b1 : 1'b0);

assign tmp_i_fu_354_p2 = ((p_0_rec_i_reg_292 == 4'd13) ? 1'b1 : 1'b0);


always @ (p_Result_24_fu_616_p3) begin
    if (p_Result_24_fu_616_p3[0] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd0;
    end else if (p_Result_24_fu_616_p3[1] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd1;
    end else if (p_Result_24_fu_616_p3[2] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd2;
    end else if (p_Result_24_fu_616_p3[3] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd3;
    end else if (p_Result_24_fu_616_p3[4] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd4;
    end else if (p_Result_24_fu_616_p3[5] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd5;
    end else if (p_Result_24_fu_616_p3[6] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd6;
    end else if (p_Result_24_fu_616_p3[7] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd7;
    end else if (p_Result_24_fu_616_p3[8] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd8;
    end else if (p_Result_24_fu_616_p3[9] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd9;
    end else if (p_Result_24_fu_616_p3[10] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd10;
    end else if (p_Result_24_fu_616_p3[11] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd11;
    end else if (p_Result_24_fu_616_p3[12] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd12;
    end else if (p_Result_24_fu_616_p3[13] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd13;
    end else if (p_Result_24_fu_616_p3[14] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd14;
    end else if (p_Result_24_fu_616_p3[15] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd15;
    end else if (p_Result_24_fu_616_p3[16] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd16;
    end else if (p_Result_24_fu_616_p3[17] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd17;
    end else if (p_Result_24_fu_616_p3[18] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd18;
    end else if (p_Result_24_fu_616_p3[19] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd19;
    end else if (p_Result_24_fu_616_p3[20] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd20;
    end else if (p_Result_24_fu_616_p3[21] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd21;
    end else if (p_Result_24_fu_616_p3[22] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd22;
    end else if (p_Result_24_fu_616_p3[23] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd23;
    end else if (p_Result_24_fu_616_p3[24] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd24;
    end else if (p_Result_24_fu_616_p3[25] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd25;
    end else if (p_Result_24_fu_616_p3[26] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd26;
    end else if (p_Result_24_fu_616_p3[27] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd27;
    end else if (p_Result_24_fu_616_p3[28] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd28;
    end else if (p_Result_24_fu_616_p3[29] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd29;
    end else if (p_Result_24_fu_616_p3[30] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd30;
    end else if (p_Result_24_fu_616_p3[31] == 1'b1) begin
        val_assign_fu_624_p3 = 32'd31;
    end else begin
        val_assign_fu_624_p3 = 32'd32;
    end
end

assign y1_fu_476_p2 = (32'd1 + x1_reg_1155);

always @ (posedge ap_clk) begin
    p_str3_load_cast_reg_1150[7] <= 1'b0;
    p_str4_load_cast_reg_1185[7] <= 1'b0;
    p_str5_load_cast_reg_1198[7:4] <= 4'b0000;
end

endmodule //xillybus_wrapper
