# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/hls-starter-1.0/coprocess/example/impl/verilog/project.cache/wt [current_project]
set_property parent.project_path C:/hls-starter-1.0/coprocess/example/impl/verilog/project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/hls-starter-1.0/coprocess/example/impl/verilog/scaled_fixed2ieee.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xilly_decprint.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xilly_decprint_out.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xilly_decprint_pobkb.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper_cud.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper_dEe.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper_eOg.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper_fYi.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper_g8j.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper_hbi.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper_ibs.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper_jbC.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper_kbM.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper_lbW.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper_mb6.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper_ncg.v
  C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper_ocq.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper.xdc
set_property used_in_implementation false [get_files C:/hls-starter-1.0/coprocess/example/impl/verilog/xillybus_wrapper.xdc]


synth_design -top xillybus_wrapper -part xc7z020clg484-1 -no_iobuf -mode out_of_context


write_checkpoint -force -noxdef xillybus_wrapper.dcp

catch { report_utilization -file xillybus_wrapper_utilization_synth.rpt -pb xillybus_wrapper_utilization_synth.pb }
