# 
# Synthesis run script generated by Vivado
# 

set_msg_config  -ruleid {1}  -id {BD 41-968}  -string {{xillybus_S_AXI}}  -new_severity {INFO} 
set_msg_config  -ruleid {2}  -id {BD 41-967}  -string {{xillybus_ip_0/xillybus_M_AXI}}  -new_severity {INFO} 
set_msg_config  -ruleid {3}  -id {BD 41-967}  -string {{xillybus_ip_0/xillybus_S_AXI}}  -new_severity {INFO} 
set_msg_config  -ruleid {4}  -id {BD 41-678}  -string {{xillybus_S_AXI/Reg}}  -new_severity {INFO} 
set_msg_config  -ruleid {5}  -id {BD 41-1356}  -string {{xillybus_S_AXI/Reg}}  -new_severity {INFO} 
set_msg_config  -ruleid {7}  -id {BD 41-759}  -string {{xlconcat_0/In}}  -new_severity {INFO} 
set_msg_config  -ruleid {8}  -id {Netlist 29-160}  -string {{vivado_system_processing_system7}}  -new_severity {INFO} 
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/xillinux-eval-zedboard-2.0a/verilog/vivado/xillydemo.cache/wt [current_project]
set_property parent.project_path C:/xillinux-eval-zedboard-2.0a/verilog/vivado/xillydemo.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/xillinux-eval-zedboard-2.0a/vivado-essentials/vivado-ip [current_project]
set_property ip_output_repo c:/xillinux-eval-zedboard-2.0a/verilog/vivado/xillydemo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet C:/hls-starter-1.0/coprocess/example/impl/ip/xillybus_wrapper.dcp
set_property used_in_implementation false [get_files C:/hls-starter-1.0/coprocess/example/impl/ip/xillybus_wrapper.dcp]
read_verilog -library xil_defaultlib {
  C:/xillinux-eval-zedboard-2.0a/verilog/src/xillydemo.v
  C:/xillinux-eval-zedboard-2.0a/verilog/src/smbus.v
  C:/xillinux-eval-zedboard-2.0a/verilog/src/i2s_audio.v
  C:/xillinux-eval-zedboard-2.0a/verilog/src/xillybus.v
  C:/xillinux-eval-zedboard-2.0a/verilog/src/xillybus_core.v
  C:/xillinux-eval-zedboard-2.0a/vivado-essentials/system.v
}
add_files C:/xillinux-eval-zedboard-2.0a/vivado-essentials/vivado_system/vivado_system.bd
set_property used_in_implementation false [get_files -all c:/xillinux-eval-zedboard-2.0a/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_0/vivado_system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/xillinux-eval-zedboard-2.0a/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/xillinux-eval-zedboard-2.0a/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/xillinux-eval-zedboard-2.0a/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/xillinux-eval-zedboard-2.0a/vivado-essentials/vivado_system/ip/vivado_system_xbar_0/vivado_system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/xillinux-eval-zedboard-2.0a/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_0/vivado_system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/xillinux-eval-zedboard-2.0a/vivado-essentials/vivado_system/vivado_system_ooc.xdc]
set_property is_locked true [get_files C:/xillinux-eval-zedboard-2.0a/vivado-essentials/vivado_system/vivado_system.bd]

read_ip -quiet C:/xillinux-eval-zedboard-2.0a/vivado-essentials/vga_fifo/vga_fifo.xci
set_property used_in_implementation false [get_files -all c:/xillinux-eval-zedboard-2.0a/vivado-essentials/vga_fifo/vga_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/xillinux-eval-zedboard-2.0a/vivado-essentials/vga_fifo/vga_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/xillinux-eval-zedboard-2.0a/vivado-essentials/vga_fifo/vga_fifo_ooc.xdc]
set_property is_locked true [get_files C:/xillinux-eval-zedboard-2.0a/vivado-essentials/vga_fifo/vga_fifo.xci]

read_ip -quiet C:/xillinux-eval-zedboard-2.0a/vivado-essentials/fifo_8x2048/fifo_8x2048.xci
set_property used_in_implementation false [get_files -all c:/xillinux-eval-zedboard-2.0a/vivado-essentials/fifo_8x2048/fifo_8x2048.xdc]
set_property used_in_implementation false [get_files -all c:/xillinux-eval-zedboard-2.0a/vivado-essentials/fifo_8x2048/fifo_8x2048_ooc.xdc]
set_property is_locked true [get_files C:/xillinux-eval-zedboard-2.0a/vivado-essentials/fifo_8x2048/fifo_8x2048.xci]

read_ip -quiet C:/xillinux-eval-zedboard-2.0a/vivado-essentials/fifo_32x512/fifo_32x512.xci
set_property used_in_implementation false [get_files -all c:/xillinux-eval-zedboard-2.0a/vivado-essentials/fifo_32x512/fifo_32x512.xdc]
set_property used_in_implementation false [get_files -all c:/xillinux-eval-zedboard-2.0a/vivado-essentials/fifo_32x512/fifo_32x512_ooc.xdc]
set_property is_locked true [get_files C:/xillinux-eval-zedboard-2.0a/vivado-essentials/fifo_32x512/fifo_32x512.xci]

set_property edif_extra_search_paths C:/xillinux-eval-zedboard-2.0a/cores [current_fileset]
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/xillinux-eval-zedboard-2.0a/vivado-essentials/xillydemo.xdc
set_property used_in_implementation false [get_files C:/xillinux-eval-zedboard-2.0a/vivado-essentials/xillydemo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top xillydemo -part xc7z020clg484-1


write_checkpoint -force -noxdef xillydemo.dcp

catch { report_utilization -file xillydemo_utilization_synth.rpt -pb xillydemo_utilization_synth.pb }
